import { Component } from 'react';
import axios from 'axios';
import Router from 'next/router';
import Head from 'next/head'
import Navigation from './../components/Navigator.js';
import { login } from '../utils/auth'

export default class Login extends Component {
  constructor(props) {
    super(props)
    this.state = {
      error: '',
      email: null,
      password: null,
    }
  }

  onInputChange = (e) => {
    this.setState({ [e.target.name]: e.target.value })
  }

  onLoginClick = async (e) => {
    e.preventDefault()
    try {
      const { email, password } = this.state;
      const url = `${process.env.API_URL}/auth/login`;
      const response = await axios.post(url, {
        email,
        password,
      })
      const { token } = response.data
      await login({ token })
      this.setState({
        token,
        error: null,
      })
      Router.push('/secure');
    } catch (error) {
      console.error(
        'You have an error in your code or there are Network issues.',
        error,
      )
      this.setState({ error: error.message })
    }
  }
  
  render() {
    return (
      <div >
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Login</h1>
        <p>Solo podes ver esto si no estas logeado.</p>
        <form onSubmit={(e) => this.onLoginClick(e)}>
          <label htmlFor="email">Email</label>
          <input
            type="text"
            id="email"
            name="email"
            placeholder="user@domain.tld"
            onChange={(e) => this.onInputChange(e)}
          />
          <label htmlFor="password">Password</label>
          <input
            type="text"
            id="password"
            name="password"
            placeholder="password"
            onChange={(e) => this.onInputChange(e)}
          />
          <button type="submit">Login</button>
          <p>{this.state.error && `Error: ${this.state.error}`}</p>
        </form>
        <Navigation />
      </div>
    )
  }
}
