import Head from 'next/head'
import Navigation from './../components/Navigator.js';
import { logout } from './../utils/auth'

function Logout() {
  return (
    <div >
      <Head>
        <title>Logout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Logout</h1>
      <p>Solo podes ver esto si acabas de deslogearte.</p>
      <Navigation/>
    </div>
  )
}

Logout.getInitialProps = async (ctx) => {
  await logout(ctx)
  return {}
}


export default Logout;