import Head from 'next/head'
import Navigation from './../components/Navigator.js';
import { handleAuthSSR } from './../utils/auth'

function Secure() {
  return (
    <div >
      <Head>
        <title>Secure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Secured page</h1>
      <p>Esta vista solo puede ser accesida si estas logeado.</p>
      <Navigation />
    </div>
  )
}

Secure.getInitialProps = async (ctx) => {
  await handleAuthSSR(ctx)
  return {}
}

export default Secure;